adobe/adobe-io-website

- templates/main/main.css
- templates/main/main.js
> just messing about

- head.html
> added in script include

- hlx_statics/scripts.js
> Adding adobe clean fonts + spectrum scale toggling

- head.html
- hlx_statics/scripts.js
- hlx_statics/styles.css
Change load order to get things rendering nicely. See comments for details!
> fix: make things load in a nice order

- head.html
Adds the class that blocks display
> fix: add class to block display

- hlx_statics/scripts.js
- hlx_statics/spectrum/minified/index.min.css
- hlx_statics/styles.css
- Change logo back to Adobe I/O
- Update nav bar height
- Added left/right padding for nav
> Nav refresh styling

- hlx_statics/blocks/site-hero.css
- hlx_statics/spectrum/minified/index.min.css
Reduce API page banner from 500px to 350px
> Reduce API page banner height

- tools/sidekick/config.js
Prep for https://github.com/adobe/helix-sidekick/issues/14
> chore(sidekick): new sidekick config

- hlx_statics/blocks/info-columns.css
- hlx_statics/scripts.js
- hlx_statics/spectrum/minified/index.min.css
- styles-includes.css
Duplicated the `Columns` block with few style changes and the child elements class assign loop. 
Unlike the `Columns` which formats first column as image (horizontal content), the `Info Columns` formats columns as vertical content and can handle more columns.
From corp Jira: [DEVSITE-55](https://jira.corp.adobe.com/browse/DEVSITE-55)
The `Info Columns` block is designed for Adobe Developer Support page's info content to be formatted into multiple columns.
Helix local preview build.
> Added `Info Columns` block for multi column info content

- hlx_statics/scripts.js
> Link updates sync

- hlx_statics/scripts.js
- hlx_statics/spectrum/minified/index.min.css
- hlx_statics/styles.css
Fixed the other header style pages not showing the search iframe.
Refactored into a decorate function to be shared between header layouts.
Some minor cleanup and ran buildCss command which applied style changes from previous commits.
Issues:
- Button style changed after previous commits need to investigate (WIP)
https://jira.corp.adobe.com/browse/DEVSITE-121
To add search to all helix pages.
Header layout 1 page:
https://search-on-all-headers--adobe-io-website--adobe.hlx.page/
Header layout 2 page:
https://search-on-all-headers--adobe-io-website--adobe.hlx.page/apis
> refactored search into decorate function and added to all headers

- hlx_statics/scripts.js
- hlx_statics/styles.css
> Fixing signin bug with search and styling

- hlx_statics/scripts.js
Added time out function to onloading postmessage attempts
Testing url:
https://local-search-frame-fix--adobe-io-website--adobe.hlx.page/
https://local-search-frame-fix--adobe-io-website--adobe.hlx.page/runtime/
> added time out for search iframe laoding after 3 seconds

- hlx_statics/blocks/header/header.js
- hlx_statics/blocks/hero/hero.js
- scripts/experimentation.js
Before: https://main--adobe-io-website--adobe.hlx.page/
After: https://fix-linting--adobe-io-website--adobe.hlx.page/
Fixes various linting issues - remain the error @ line 102 of `header.js` that I would kindly ask someone who knows this code to fix.
- [ x] Bug fix (non-breaking change which fixes an issue)
> chore: fix linting

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/header/header.js
Adding a distribute button to the creative-cloud page. 
Adding the distribute button when the pathname contains developer/distribution
https://jira.corp.adobe.com/browse/DEVSITE-659
TestingURL:
https://louisa-devsite-659-distribute-button--adobe-io-website--adobe.hlx.page/
> Adding Distribute button

- hlx_statics/blocks/header/header.js
- hlx_statics/scripts/lib-adobeio.js
This PR fixes a problem with the search functionality on the website that caused a 404 error due to an issue with the search-frame origin selection. The fix involves adding a new function called setSearchFrameOrigin which is a modified version of setExpectedOrigin and uses the stage iFrame src on hlx host. Additionally, a specific query parameter check was added to prevent the search from triggering when any query string is present. Finally, the code was updated to fix some issues identified by the linter. These changes should improve the functionality and reliability of the search functionality on the website.
Testing urls:
https://searchfixes--adobe-io-website--adobe.hlx.page/
> Fix search-frame origin 404, added specific query parameter check, lint fixes

- hlx_statics/blocks/announcement/announcement.js
- hlx_statics/blocks/api-browser/api-browser.js
- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/columns/columns.js
- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/hero/hero.js
- hlx_statics/blocks/info-columns/info-columns.js
- hlx_statics/blocks/info/info.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/styles/styles.css
https://jira.corp.adobe.com/browse/DEVSITE-664 - when section metadata is set to dark, apply the spectrum dark color and make the text color to be white.
Testing URL
https://dev-664-darktheme--adobe-io-website--adobe.hlx.page/photoshop/index-new
> feat: dark section styling

- hlx_statics/blocks/table/table.css
- hlx_statics/blocks/table/table.js
- hlx_statics/styles/spectrum/spectrum.min.css
Implementation fo table using spectrum css
Implementation 
https://devsite-665-table--adobe-io-website--adobe.hlx.page/photoshop/index-new
> feat: table

- hlx_statics/styles/spectrum/spectrum.min.css
Fix dark mode for table
The heading wasn't picikign the right color in dark mode
You can check the end-result here
**https://devsite-665-table-fix-dark-mode--adobe-io-website--adobe.hlx.page/photoshop/index-new**
> fix: table dark mode

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/header/header.js
Adding css to Mobile responsive 
Adding css for the global nav to add responsiveness  for mobility
> Update on Header mobile responsive

- hlx_statics/blocks/header/header.css
Hero is blocking the popover.
Adding the zindex of popover to be larger. 
[DEVSITE 672](https://jira.corp.adobe.com/browse/DEVSITE-672)
> update z-index to override the hero

- hlx_statics/blocks/header/header.css
Update z-index on header to 1001
Update z-index on header to 1001
> Update on z-index

- hlx_statics/blocks/header/header.css
Update global header css
Update global header css
> Update global header

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/header/header.js
Fix issue with header buttons and hero container
Fix issue with header buttons and hero container
> Fix issue with header buttons and hero container

- hlx_statics/blocks/header/header.js
Adding a distribution link guard 
Adding a distribution link guard
> Adding distribution guard

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/header/header.js
removing from the correct parent
removing from the correct parent
> removing from the correct parent

- hlx_statics/blocks/header/header.js
Update safari header text
Update safari header text
> Update safari header text

- hlx_statics/blocks/announcement/announcement.css
- hlx_statics/blocks/announcement/announcement.js
This fixes the new feature that needs overlapping of animated gif in the first announcement page
This fixes #48 
You can test the end solution here:
https://48-announcement-video--adobe-io-website--adobe.hlx.page/photoshop/index-new
> 48 announcement video

- hlx_statics/blocks/header/header.css
Update on console search button
Update on console search button
> Update on console search button

- hlx_statics/blocks/footer/footer.css
- hlx_statics/blocks/header/header.css
Fixed footer CLS as per
Run local LHS
TestURL: https://fix-footer-cls--adobe-io-website--adobe.hlx.page/empty-test-dj
> fix: footer cls

- hlx_statics/blocks/header/header.js
Update css of the distribute button
Adding the class spectrum-button--cta and spectrum-button-fill
https://jira.corp.adobe.com/browse/DEVSITE-688
> Update css of the distribute button

- hlx_statics/blocks/header/header.js
Update distribute mobile button to stack
Update distribute mobile button to stack
https://jira.corp.adobe.com/browse/DEVSITE-688
> Update distribute mobile button to stack

- hlx_statics/blocks/header/header.css
Fix the problem of double-scrolling
Fix the problem of double-scrolling
https://jira.corp.adobe.com/browse/DEVSITE-694
> Fix the problem of double-scrolling

- hlx_statics/blocks/carousel/carousel.css
- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/site-hero/site-hero.css
- hlx_statics/blocks/site-hero/site-hero.js
- hlx_statics/scripts/lib-adobeio.js
Edited the site hero component
DEVSITE-830
Component wasn't rendering how it should have
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
> Site hero component

- hlx_statics/blocks/api-browser/api-browser.css
- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/footer/footer.css
- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/hero/hero.css
- hlx_statics/blocks/site-hero/site-hero.css
- hlx_statics/blocks/summary/summary.css
Update for css on mobile
Update for css on mobile
https://jira.corp.adobe.com/browse/DEVSITE-816
> Update for css on mobile

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/site-hero/site-hero.css
Fix the Hero image on mobile
Fix the Hero image on mobile
DEVSITE-816
> Update on site-hero

- hlx_statics/blocks/site-hero/site-hero.css
update the width
update the width
devsite-816
> update the width

- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/site-hero/site-hero.css
Migrate Mini Resource Cards to franklin
> Mini resource cards

- hlx_statics/blocks/api-browser/api-browser.css
- hlx_statics/blocks/api-browser/api-browser.js
fixing accessibility for product page 
https://jira.corp.adobe.com/browse/A11Y-5442
https://jira.corp.adobe.com/browse/A11Y-5443
https://jira.corp.adobe.com/browse/A11Y-5444
https://jira.corp.adobe.com/browse/A11Y-5445
https://jira.corp.adobe.com/browse/A11Y-5449
> fixing accessibility

- hlx_statics/blocks/api-browser/api-browser.js
adding ariaExpand
adding ariaExpand
https://jira.corp.adobe.com/browse/A11Y-5446
> Adding ariaExpand

- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/columns/columns.js
- hlx_statics/blocks/info/info.css
- hlx_statics/blocks/info/info.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/scripts/scripts.js
Adding Anchor link to column and info
Adding Anchor link to column and info
DEVSITE-845
> devsite 845 anchor link

- hlx_statics/blocks/accordion/accordion.css
- hlx_statics/blocks/accordion/accordion.js
> Merge accordion content block

- hlx_statics/blocks/accordion/accordion.css
- hlx_statics/blocks/accordion/accordion.js
- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
added section metadata for the option to make the background color white
> Background color

- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/columns/columns.js
Update background-color to white for columns when it's specified in metadata
https://jira.corp.adobe.com/browse/DEVSITE-856
> Update background-color for column

- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/columns/columns.js
Change css when there is bullet listings
Change css when there is bullet listings
DEVSITE-900-bullet-list
> Change css when there is bullet listings

- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/cards/cards.js
- hlx_statics/scripts/lib-helix.js
update card to use links instead of buttons
update card to use links instead of buttons
[DEVSITE-857](https://jira.corp.adobe.com/browse/DEVSITE-857)
> update card to use links

- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/columns/columns.js
Update column to match photoshop pricing
Update column to match photoshop pricing
https://jira.corp.adobe.com/browse/DEVSITE-858
> Update column pricing

- tools/sidekick/config.json
- tools/sidekick/library.html
Adding files for sidekick
Adding files for sidekick
devsite-864-franklin page sidekick library
> Adding files for sidekick

- tools/sidekick/config.json
add side kick library files
add side kick library files
devsite-864
> side kick library

- hlx_statics/blocks/accordion/accordion.css
- hlx_statics/blocks/accordion/accordion.js
- hlx_statics/blocks/announcement/announcement.js
- hlx_statics/blocks/api-browser/api-browser.js
- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/columns/columns.js
- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/info-columns/info-columns.js
- hlx_statics/blocks/info/info.js
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/resource-card/resource-card.js
- hlx_statics/blocks/table/table.js
- hlx_statics/scripts/lib-adobeio.js
Fix the Component width and background color through the section metadata
Custom Background Color and Width through section metadata
devsite-935
> Custom Background Color and Width through section metadata

- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/embed/embed.js
Embed component not rendered when there is no width
Embed component not rendered when there is no width
https://jira.corp.adobe.com/browse/DEVSITE-935
> fix the problem with embed components not work with no width

- hlx_statics/blocks/header/header.js
The developer-distribution change in url needs to update the check for the button.
The developer-distribution change in url needs to update the check for the button.
> update developer-distrubution url

- hlx_statics/scripts/lib-adobeio.js
Need to maintain the old style
Need to maintain the old style
> update to be able to use old style

- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/resource-card/resource-card.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/styles/styles.css
Adding seciton title to cards
https://jira.corp.adobe.com/browse/DEVSITE-936
> Adding section title to cards

- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/resource-card/resource-card.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/styles/styles.css
update section title
devsite-936
> update section title

- hlx_statics/blocks/site-hero/site-hero.js
fix the problem with different fonts with link
https://jira.corp.adobe.com/browse/DEVSITE-938
> update link fonts

- hlx_statics/blocks/resource-card/resource-card.css
Update Resource card limited to 1280px 
devsite-945
> Update resource card cap at 1280px

- hlx_statics/blocks/resource-card/resource-card.css
update the content bottom padding
devsite-945
> update the padding bottom on content

- hlx_statics/blocks/video-carousel/video-carousel.css
- hlx_statics/blocks/video-carousel/video-carousel.js
Add Video Carousel 
devsite-838
> Add video carousel

- hlx_statics/blocks/hero/hero.js
- hlx_statics/blocks/site-hero/site-hero.js
remove serif font in hero and site hero
devsite 937
> devsite 937 font family

- hlx_statics/blocks/hero/hero.js
- hlx_statics/blocks/site-hero/site-hero.js
Use any font family
devsite-937
> update to use any font family

- .idea/inspectionProfiles/Project_Default.xml
- hlx_statics/blocks/video-carousel/video-carousel.css
- hlx_statics/blocks/video-carousel/video-carousel.js
update video carousel
devsite838
> update video carousel with youtube links

- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
adding the analytics for the missing components. 
devsite 840
> adding analytics

- hlx_statics/blocks/video-carousel/video-carousel.js
> update video tag with controls

- hlx_statics/blocks/accordion/accordion.js
- hlx_statics/blocks/announcement/announcement.js
- hlx_statics/blocks/api-browser/api-browser.js
- hlx_statics/blocks/banner/banner.js
- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/columns/columns.js
- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/hero/hero.js
- hlx_statics/blocks/info-columns/info-columns.js
- hlx_statics/blocks/info/info.js
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/resource-card/resource-card.js
- hlx_statics/blocks/site-hero/site-hero.js
- hlx_statics/blocks/summary/summary.js
- hlx_statics/blocks/table/table.js
- hlx_statics/blocks/video-carousel/video-carousel.js
- hlx_statics/scripts/lib-adobeio.js
Adding an override to analytic headings. 
devsite-840
> Update on custom analytics

- hlx_statics/blocks/columns/columns.js
- hlx_statics/blocks/header/header.js
- hlx_statics/blocks/summary/summary.js
- hlx_statics/styles/styles.css
> Adding back some more lost styles

- hlx_statics/icons/ribbon.svg
- hlx_statics/icons/ribbon_purple.svg
https://main--adobe-io-website--adobe.hlx.page/developer-champion/
URL for testing: https://main--adobe-io-website--adobe.hlx.page/developer-champion/
https://main--adobe-io-website--adobe.hlx.page/developer-champion/
- https://main--adobe-io-website--adobe.hlx.live/
- https://stage--adobe-io-website--adobe.hlx.page/
> Ribbon for Developer Champion website

- hlx_statics/blocks/carousel/carousel.js
Fixed functionality for adding hyperlinked images into a carousel component.
Added reformatHyperlinkImages function to reformat HTML.
Added an if statement to create proper left/right containers for hyperlinked images
Jira ticket: [link](https://jira.corp.adobe.com/browse/DEVSITE-1185)
Erin asked for it a couple days ago on Slack. Allows hyperlinked images to be in carousels
I created a carousel with a few hyperlinked and regular images and tested that the hyperlinks and images were formatted correctly. The hyperlinks also work. Here's a link to the google doc I used to test: [link](https://docs.google.com/document/d/1Zqt5QOX_Y7L5_6WseWbgW5Y8uLDGOqADlMYG1-wbg1E/edit)
Note that the first 2 images are hyperlinked and the last is not.
The old functionality:
New Functionality:
- [x ] Bug fix …
> fix: Allowing Images with Hyperlinks

- hlx_statics/blocks/title/title.css
- hlx_statics/blocks/title/title.js
> Devsite 1171 Title Block

- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
EDS equivalent of Gatsby [InlineCode](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/InlineCode/index.js#L19) block
https://jira.corp.adobe.com/browse/DEVSITE-1135
Started with a [lint](https://github.com/adobe/adobe-io-website/pull/147/commits/1fdba6c3963991ea1f3d5b364d1362116479f200) commit so that the [inline code](https://github.com/adobe/adobe-io-website/pull/147/commits/2afbf68aab9ce2a5de01a01f33dbd27e891abec4) commit is easier to read.
> InlineCode block

- hlx_statics/blocks/discover/discover.css
- hlx_statics/blocks/discover/discover.js
> build : Add discover & multiple discover block

- hlx_statics/blocks/tab/tab.css
- hlx_statics/blocks/tab/tab.js
> build : Added tab block

- hlx_statics/blocks/teaser/teaser.css
- hlx_statics/blocks/teaser/teaser.js
> Devsite 1171 Teaser

- hlx_statics/blocks/image-text/image-text.css
- hlx_statics/blocks/image-text/image-text.js
> Devsite 1171 ImageTextBlock

- hlx_statics/blocks/text/text.css
- hlx_statics/blocks/text/text.js
> Created text block

- hlx_statics/blocks/heading1/heading1.css
- hlx_statics/blocks/heading1/heading1.js
- hlx_statics/blocks/heading2/heading2.css
- hlx_statics/blocks/heading2/heading2.js
- hlx_statics/blocks/heading3/heading3.css
- hlx_statics/blocks/heading3/heading3.js
- hlx_statics/blocks/heading4/heading4.js
- hlx_statics/blocks/heading5/heading5.js
- hlx_statics/blocks/heading6/heading6.js
- hlx_statics/components/divider.js
- hlx_statics/components/heading.js
- hlx_statics/components/link.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
EDS equivalents of the following Gatsby blocks:
- [Heading1](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L136)
- [Heading2](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L137)
- [Heading3](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L138)
- [Heading4](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L139)
- [Heading5](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L140)
- [Heading6](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/Heading/index.js#L141)
> Heading blocks

- hlx_statics/blocks/resource/resource.css
- hlx_statics/blocks/resource/resource.js
> add : resource block

- hlx_statics/blocks/product-card/product-card.css
- hlx_statics/blocks/product-card/product-card.js
> Add : Product card

- hlx_statics/blocks/dcsummary/dcsummary.css
- hlx_statics/blocks/dcsummary/dcsummary.js
> Add : DC Summary block

- hlx_statics/blocks/resource-card/resource-card.css
Made resource cards wrap better so that more than 3 can be put in at a time. It also automatically fixed the mobile view which was a plus.
Just added some CSS and flex-wrap stuff so that images would collapse to column view. 
Needs to have more than 3 resource cards. The Jira ticket is [here](https://jira.corp.adobe.com/browse/DEVSITE-949) but it doesn't not mention mobile view modification, Pat and I just decided to fix this.
I just put everything into different mobile views to test. The test link is [here](https://devsite-949--adobe-io-website--adobe.hlx.page/test/Eli/949-large-rc-size).
> RC card improvement

- hlx_statics/blocks/columns/columns.css
Pat and I looked through the columns in mobile view and it didn't look too great, so I modified it so that everything became center-justified in mobile view. [This](https://jira.corp.adobe.com/browse/DEVSITE-948) is the jira ticket, but it didn't say anything for mobile view, Pat and I came up with this ourselves.
Makes accessibility better
The test link could be found [here](https://devsite-948--adobe-io-website--adobe.hlx.page/test/Eli/948-column-size). Note that the first 4 images are the correct size, the rest are not relevant. If you minimize the browser window to a more mobile view, you will see everything moving to center justification
> Made mobile view better for Columns

- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/columns/columns.js
Icons only displayed small if followed by a link. 
I made an if statement so that that even text gets added to the product link container div. I also enwrapped non-links in an paragraph tag with class "icon-text", so that there would be some space between the icon and the text next to it.
[Jira Ticket](https://jira.corp.adobe.com/browse/DEVSITE-1192)
Icons should be able to have non-linked text associated with them without becoming huge.
I just modified the code and checked if the DOM was intact. I looked at it on localhost and the images came out to the right size.
https://docs.google.com/document/d/1RphfPEBfnnFrOAm1nPrmdks8VTjdQRtPTgTwuVsL0Jc/edit
^This is Erin's original google doc that caused the errors
[This is my copy](https://docs.google.com/document/d/1JXEvSKLnYuSaBdunL_n7VXcksab6o …
> Devsite 1192: Icons with Links formatting

- hlx_statics/blocks/resource-card/resource-card.css
- hlx_statics/blocks/resource-card/resource-card.js
Idk how I didn't see this before, but the resource cards aren't aligned in the mobile view due to some weird margins. I just took that out and made sure that the cards actually fit the 400 by 200 image. 
no Jira ticket, just a lil clean up.
IT WAS SO UGLY :(
I used [this doc](https://docs.google.com/document/d/1MXdSU5AhIrJ_tRHMiyBukymcyZ3ACM4BBgmoKfGuMuc/edit)
The test link for my changes is [here](https://devsite-949--adobe-io-website--adobe.hlx.page/test/Eli/949-large-rc-size)
Current RC:
New RC:
> Fix Mobile view for RC Cards

- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/embed/embed.js
I got rid of all the spectrum css in the embed.css file to minify the size of the css
Getting rid of spectrum in our css.
HACKATHON 🥳 
I tested it by comparing my branch:
[Eli's Hackathon demo Doc](https://eli--adobe-io-website--adobe.hlx.page/test/Hackathon/eli)
I looked at the difference between that and the normal site:
[Main Hackathon Site](https://main--adobe-io-website--adobe.hlx.page/test/Hackathon/eli)
I also tried testing it with different embed links from my demo doc:
[Eli's branch for demo doc](https://eli--adobe-io-website--adobe.hlx.page/test/Eli/demo-doc)
I just looked at the diff between my branch and stage for that doc:
[Stage Demo Doc](https://stage--adobe-io-website--adobe.hlx.page/test/Eli/demo-doc)
> Got Rid of Spectrum css in Embed block

- hlx_statics/blocks/video-carousel/video-carousel.js
Video carousel is now formatted correctly. I added some js code to correctly redecorate the block.
Due to changes in decoration in lib-adobeio.js, html was not rendered correctly. 
HACKATHON 🥳 
[This](https://vidcarousel--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) is the link with the correct video carousel.
[This](https://fresh-spectrum-less--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) is what it looked like before.
Old pic:
New pic:
> Video carousel

- hlx_statics/blocks/summary/summary.css
- Remove dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [summary](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less-column-styles/hlx_statics/blocks/summary)
- Minor styling fixes for responsiveness
- ~Accessibility fixes~
Hackathon
https://specless-summary-block--adobe-io-website--adobe.hlx.page/test/Hackathon/dmitry
Lighthouse & AXE Accessibility DevTools
No accessibility issues found with AXE.
Lighthouse (localhost):
Lighthouse (helix host):
> Remove summary spectrum

- hlx_statics/blocks/columns/columns.css
Removing dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [columns](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less-column-styles/hlx_statics/blocks/columns)
Hackathon
https://fresh-spectrum-less-column-styles--adobe-io-website--adobe.hlx.page/test/Hackathon/melissa
Lighthouse:
axe DevTools:
> column styles

- hlx_statics/blocks/info/info.css
Removing dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [info](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less/hlx_statics/blocks/info)
Hackathon
https://fresh-spectrum-less-info-styles--adobe-io-website--adobe.hlx.page/test/Hackathon/melissa
Lighthouse:
axe DevTools:
> Info styles

- hlx_statics/blocks/info-columns/info-columns.css
Removing dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [info-columns](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less/hlx_statics/blocks/info-columns)
Hackathon
https://fresh-spectrum-less-info-column-styles--adobe-io-website--adobe.hlx.page/test/Hackathon/melissa
Lighthouse:
axe DevTools:
> Info column styles

- hlx_statics/blocks/header/header.js
Fix top nav to be able to be called from anywhere without running into cors errors.
> Fresh spectrum top nav

- hlx_statics/blocks/announcement/announcement.css
Removing dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [announcement](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less/hlx_statics/blocks/announcement)
Hackathon
https://announcement-styles--adobe-io-website--adobe.hlx.page/test/Hackathon/melissa
> Announcement styles

- hlx_statics/blocks/banner/banner.css
Removing dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [banner](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less/hlx_statics/blocks/banner)
Hackathon
https://banner-styles--adobe-io-website--adobe.hlx.page/test/Hackathon/melissa
> Banner styles

- hlx_statics/blocks/hero/hero.css
- hlx_statics/blocks/site-hero/site-hero.css
- hlx_statics/blocks/site-hero/site-hero.js
- hlx_statics/blocks/summary/summary.css
- Remove dependency on [spectrum.min.css](https://github.com/adobe/adobe-io-website/blob/fresh-spectrum-less/hlx_statics/styles/spectrum/spectrum.min.css) from [hero](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less-column-styles/hlx_statics/blocks/hero) and [site-hero](https://github.com/adobe/adobe-io-website/tree/fresh-spectrum-less-column-styles/hlx_statics/blocks/site-hero)
- Minor styling fixes for responsiveness
- Update summary block css to use rgb values instead of hex
- ~Accessibility fixes~
https://specless-hero-block--adobe-io-website--adobe.hlx.page/test/Hackathon/dmitry
Lighthouse & AXE Accessibility DevTools
No accessibility issues found with AXE.
Lighthouse (localhost):
Lighthouse (helix host):
> Specless hero block

- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/cards/cards.js
- hlx_statics/blocks/hero/hero.css
- hlx_statics/blocks/hero/hero.js
- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
- hlx_statics/blocks/teaser/teaser.css
- hlx_statics/blocks/teaser/teaser.js
- hlx_statics/blocks/text/text.css
- hlx_statics/blocks/text/text.js
> Made some CSS enhancement to the blocks for the Express add-ons

- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/summary/summary.css
I added section metadata for the video title and then added thumbnail capability for google drive. Got rid of autoplay functionality.
Making Lighthouse score higher for embed block
HACKATHON 🥳 
This is the [link](https://embed--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) to test it on the hackathon page.
> Modified embed functionality

- hlx_statics/blocks/carousel/carousel.css
- hlx_statics/blocks/carousel/carousel.js
- hlx_statics/blocks/video-carousel/video-carousel.css
- hlx_statics/blocks/video-carousel/video-carousel.js
Made Image and video carousel mobile friendly, got rid of spectrum stuff, added infinite scrolling capability, added some button labels for accessibility. 
Lack of accessibility and responsiveness. Spectrum bad >>>>>>
HACKATHON 🥳 
I used [this](https://imgcarousel--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) link to look at the Hackathon page.
[This](https://fresh-spectrum-less--adobe-io-website--adobe.hlx.page/test/Eli/carousels) is what it looks like with just the carousels.
> Carousels Mobile Friendly

- hlx_statics/blocks/info-card/info-card.js
Fixed queryselector error
https://spectrum-less-resource--adobe-io-website--adobe.hlx.page/test/Hackathon/diane
> fix queryselector error

- hlx_statics/blocks/columns/columns.css
Made images resize for mobile (phone) view
Change some CSS
HACKATHON 🥳 
[This](https://columns--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) is the link to my updated branch
[This](https://fresh-spectrum-less--adobe-io-website--adobe.hlx.page/test/Hackathon/eli) is the current implementation on fresh-spectrum-less.
Old implementation:
https://github.com/user-attachments/assets/ab4bafe8-090d-43d2-9d8d-8ed0a826e2f0
New Implementation (center justified text, image resized):
https://github.com/user-attachments/assets/90ff8a99-a1ef-4f15-9873-e58f0e134259
> Columns more mobile Friendly

- hlx_statics/blocks/product-card/product-card.css
- hlx_statics/blocks/profile-card/profile-card.css
Remove spectrum from Product and profile cards.
Change CSS.
https://jira.corp.adobe.com/browse/DEVSITE-1254
HACKATHON 🥳 
Here's a test [link](https://devsite-1254--adobe-io-website--adobe.hlx.page/test/product-card)
> fix: remove spectrum

- hlx_statics/blocks/tab/tab.css
- hlx_statics/blocks/tab/tab.js
Optimized tab block
https://tab_spectrum_less--adobe-io-website--adobe.hlx.page/test/tab
> --Optimized & made some customization in tab block

- hlx_statics/blocks/teaser/teaser.css
- hlx_statics/blocks/teaser/teaser.js
> Removed unwanted code

- hlx_statics/blocks/profile-card/profile-card.css
- hlx_statics/blocks/profile-card/profile-card.js
> Optimized profile card

- hlx_statics/blocks/resource/resource.js
Modified javascript for resource block so extra link doesn't appear in HTML
https://jira.corp.adobe.com/browse/DEVSITE-1231
Hackathon 🥳 
[This](https://fresh-spectrum-merge--adobe-io-website--adobe.hlx.page/test/resource) is the current environment
[This](https://devsite-1231--adobe-io-website--adobe.hlx.page/test/resource) is the new one.
Old block (extra link elem):
New block:
> fix:remove extra link in Resource Block

- hlx_statics/blocks/image-text/image-text.css
- hlx_statics/blocks/image-text/image-text.js
> Optimized image-text block

- hlx_statics/blocks/text/text.js
- hlx_statics/styles/styles.css
Optimized & Customized Text block
https://text-spectrum-less--adobe-io-website--adobe.hlx.page/test/text
> --Optimized & Customized Text block

- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/iframe/iframe.css
- hlx_statics/blocks/iframe/iframe.js
Changed up css/js for accessibility and lighthouse
https://jira.corp.adobe.com/browse/DEVSITE-1256
HACKATHON 🥳 
[Here's](https://iframe--adobe-io-website--adobe.hlx.page/test/Eli/iframe) my branch
[Here's](https://fresh-spectrum-less--adobe-io-website--adobe.hlx.page/test/Eli/iframe) the old branch
> Optimize iframe

- hlx_statics/scripts/scripts.js
> Footer grid

- hlx_statics/blocks/columns/columns.js
Columns line break fix
Able to add link in the middle of a paragraph without it breaking in columns
> Columns line break fix

- hlx_statics/blocks/contributors/contributors.css
- hlx_statics/blocks/contributors/contributors.js
- hlx_statics/styles/styles.css
Contributors component 
This block is created with the static content but needs to update the content with the GitHub details
https://contributors-spectrum-less--adobe-io-website--adobe.hlx.page/test/contributors
> Contributors spectrum less

- hlx_statics/blocks/onthispage/onthispage.css
- hlx_statics/blocks/onthispage/onthispage.js
EDS- Convert OnThisPage
https://devsite-1240-onthispage-spectrum-less--adobe-io-website--adobe.hlx.page/test/documentation
> Devsite 1240 onthispage spectrum less

- hlx_statics/blocks/edition/edition.css
- hlx_statics/blocks/edition/edition.js
EDS - Convert Edition (DevDocs)
https://devsite-1235-edition-spectrum-less--adobe-io-website--adobe.hlx.page/test/edition
> Devsite 1235 edition spectrum less

- hlx_statics/scripts/delayed.js
- hlx_statics/scripts/scripts.js
Improve loading performance
Created a separate function to load IMS and moved it from delayed to loadLazy. Also moved other things from delayed to loadLazy and vice versa to improve loading performance. 
IMS should be loaded fairly quickly as it is used for other things
> Improve loading performance

- hlx_statics/blocks/contributors/contributors.css
- hlx_statics/blocks/contributors/contributors.js
Contributors Component
Encountered feedback model open issues on the contributor's component. It was working fine in the local and test URL but after merge it hasn't worked on the live. So I fixed those issues in this PR.
https://feedback-modal-issue--adobe-io-website--adobe.hlx.page/test/contributors
> Feedback Modal issues

- hlx_statics/blocks/teaser/teaser.js
- hlx_statics/components/actionButton.js
- hlx_statics/styles/styles.css
Decorate Action Button
https://decorate-action-button--adobe-io-website--adobe.hlx.page/test/teaser
> Decorate ActionButton

- hlx_statics/blocks/header/header.css
- hlx_statics/blocks/header/header.js
- hlx_statics/styles/styles.css
https://devsite-1288-version-switcher--adobe-io-website--adobe.hlx.page/
> added the version switcher

- hlx_statics/blocks/link/link.css
- hlx_statics/blocks/link/link.js
- hlx_statics/styles/styles.css
Converted Link block
https://link-spectrum-less--adobe-io-website--adobe.hlx.page/test/link
> created the link block

- hlx_statics/blocks/inline-nested-alert/inline-nested-alert.css
- hlx_statics/blocks/inline-nested-alert/inline-nested-alert.js
Inline Nested Alert Block: Bug Fixes and Performance Enhancements.
Best Practices between 70 and 80 because of "Uses deprecated APIs".
https://bug-fix-inline-nested-alert-block--adobe-io-website--adobe.hlx.page/test/inline-nested-alert
> Inline Nested Alert Block : Bug Fixes and Performance Enhancements

- hlx_statics/styles/styles.css
Removed spectrum in the Inline code
> Spectrum less - Inline code

- hlx_statics/blocks/tab/tab.css
Made mobile and tab responsive
https://secondpass-tab-block--adobe-io-website--adobe.hlx.page/test/code-tab-block
> Bug : Made responsive

- hlx_statics/blocks/onthispage/onthispage.css
- hlx_statics/blocks/onthispage/onthispage.js
Anchor tag attributes have been added and some unnecessary css removed.
Best Practices between 70 and 80 because of "Uses deprecated APIs".
https://bug-fix-onthispage-block--adobe-io-website--adobe.hlx.page/test/onthispage
> Onthispage Block : Anchor tag attributes have been added.

- hlx_statics/blocks/heading2/heading2.css
- hlx_statics/blocks/heading3/heading3.css
- hlx_statics/styles/styles.css
Removed spectrum in the Heading level 1 to 6
https://second-pass-heading--adobe-io-website--adobe.hlx.page/test/heading
> Heading : Removed spectrum

- hlx_statics/blocks/codeblock/codeblock.css
- hlx_statics/blocks/codeblock/codeblock.js
Optimized to improve performance
https://bug-fix-code-block--adobe-io-website--adobe.hlx.page/tools/sidekick/blocks/codeblock
Implemented the function to create button.
> Code Block : Optimized to improve performance.

- hlx_statics/blocks/header/header.css
Added the mobile responsiveness
https://bug-fix-version-switcher--adobe-io-website--adobe.hlx.page/franklin_assets/nav#
> Version Switcher : Added the mobile responsiveness

- hlx_statics/blocks/inlinealert/inlinealert.js
Updated the info variant as default variant
https://fix-inlinealert--adobe-io-website--adobe.hlx.page/test/inlinealert
> fix : updated the info variant as default variant

- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/carousel/carousel.css
- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/resource-card/resource-card.css
- hlx_statics/styles/styles.css
Fixing the carousel and column issue
> Fix column and carousel styles

- hlx_statics/blocks/announcement/announcement.css
- hlx_statics/blocks/api-browser/api-browser.css
- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/info-columns/info-columns.css
- hlx_statics/blocks/info/info.css
- hlx_statics/blocks/resource-card/resource-card.css
- hlx_statics/blocks/table/table.css
- hlx_statics/styles/styles.css
The background color is the same grey as the footer, it shouldn't be.
It should be a slightly darker gray of 245,245,245
> update corrent background color

- hlx_statics/blocks/cards/cards.css
fix the card width properly for 4 cards.
> fix 4 card width

- hlx_statics/blocks/cards/cards.css
Fixing the card layout to show 4 max in a row and fix the mobile version to lay out better.
> Fixing the card to layout better

- hlx_statics/blocks/carousel/carousel.css
- hlx_statics/blocks/hero/hero.css
- hlx_statics/styles/styles.css
Update default font sizes and match main branch
update carousel button size to be 12px by 12px
> update font sizes and carousel button

- hlx_statics/blocks/accordion/accordion.css
- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/footer/footer.css
- hlx_statics/styles/styles.css
Update on the font size changes
> update on some fontsize changes

- hlx_statics/blocks/columns/columns.css
column width on ipad needs to be fixed without 100%
> Column ipad fix

- hlx_statics/blocks/carousel/carousel.js
Make sure it doesn't remove the child when it's null.
> Update bug fix
